spring:
  datasource:
    url: mysql://b72676c1138f8f:d388b853@eu-cdbr-west-03.cleardb.net/heroku_d75b67b266e31ca?reconnect=true
    username: b72676c1138f8f
    password: d388b853
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: ${PORT:8080}